// Lexical grammar (tokens)
%lex

%%

\s+                   /* Ignore whitespace */
\"[^\"]*\"            return 'STRING';
\d+                   return 'NUMBER';
true|false            return 'BOOLEAN';
[\w\+*-=<>/]+         return 'SYMBOL';
.                     return 'UNKNOWN';

/lex

// Syntactic grammar (BNF)
%%

Exp
  : Atom
  | List
  ;

Atom
  : NUMBER { $$ = Number(yytext); }
  | STRING { $$ = yytext; }
  | BOOLEAN { $$ = (yytext === 'true'); }
  | SYMBOL { $$ = yytext; }
  ;

List
  : '(' ListEntries ')' { $$ = $2; }
  ;

ListEntries
  : ListEntries Exp { $1.push($2); $$ = $1; }
  | /* empty */     { $$ = []; }
  ;

